In [137]:
import pandas as pd
# ^^^ pyforest auto-imports - don't write above this line
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import math

<span style="font-family: Arial; font-weight:bold;font-size:1.5em;color:#7d5b06;">1. Within a school district, students were randomly assigned to one of two Math teachers - Mrs. Smith and Mrs. Jones. After the assignment, Mrs. Smith and Mrs. Jones had 30 students each.At the end of the year, each class took the same standardized test. The scores are of students are given below.Test the hypothesis that weather Mrs. Smith and Mrs. Jones are equally effective teachers. Use a 0.05 level of significance.


Mrs_Smith = [66,68,71,62,63,63,88,87,89,85,98,91,54,53,69,58,70,86,84,87,87,66,61,60,56,77,75,71,70,59,62,63]

Mrs_Jones = [71,80,81,87,64,68,60,72,71,77,39,88,63,55,64,63,71,71,48,63,77,49,67,69,56,44,48,77,63,88,67,67]

A. Frame Null and Alternate Hypothesis ( 1 Mark)

B. State which test to be performed  (1 Mark)

C. Perform the test  (2 Mark)

D. Interpret the results  (1 Mark)

#### A.Frame Null and Alternate Hypothesis

* Null hypothesis: μ1 - μ2 = 0 (Both of them eually effective, there is no difference)

* Alternative hypothesis: μ1 - μ2 ≠ 0 (Both of them are not equally effective there is a difference)

#### B.State which  test to be performed

* Two tail 2-Sample t test to be Performed

#### C.Perform the test  

In [14]:
Mrs_Smith = [66,68,71,62,63,63,88,87,89,85,98,91,54,53,69,58,70,86,84,87,87,66,61,60,56,77,75,71,70,59,62,63]

Mrs_Jones = [71,80,81,87,64,68,60,72,71,77,39,88,63,55,64,63,71,71,48,63,77,49,67,69,56,44,48,77,63,88,67,67]

In [15]:
from scipy.stats import ttest_ind

In [16]:
ttest_ind(Mrs_Smith,Mrs_Jones)

Ttest_indResult(statistic=1.7081743311361917, pvalue=0.09260670088904191)

#### D.Interpret the results

* Here the p_value is less than greater than 0.05 so we fail to reject the null hypothesis.

<span style="font-family: Arial; font-weight:bold;font-size:1.5em;color:#7d5b06;">2.Read the dataset (Churn.xlsx) it consists of all the information regarding telecom industry for any telecom industry Churning rate of customers causes direct impact on the business so by performing the statistical analysis on the data set we need to find out on what facors the churning rate is dependent on. Perform the following tasks on the data :

1. List out the numerical and categorical features in the dataset and mention the possible statistical hypothesis test for give features in the dataset(2 marks)


2. State the null and alternative hypothesis for any one of the test mention in the question number one(2 marks)

3. Now perform any two required statistical test on the data to determine what are the significant features in the data with respect to target variable(95% C.I ) ? (4 Marks)

4. Interpret the results ? (2 Marks)

#### 1. List out the numerical and categorical features in the dataset and mention the possible statistical hypothesis test for give features in the dataset(2 marks)


In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_excel("Churn.xlsx")

#### 2. State the null and alternative hypothesis for any one of the test mention in the question number one(2 marks)

#### 2 sample t-test


#### Null Hypothesis : 

H0 : There is no significant differnece between the means of variables.

#### Alternate Hypothesis :

H1 : There is a significant differnece between the means of variables.

Chi-Square test :

#### Null Hypothesis : 

H0 : There is no dependancy between the variables.

#### Alternate Hypothesis :

H1 : There is a dependancy between the variables.

#### 3. Now perform required statistical tests on the data to determine what are the significant features in the data with respect to  target variable(95%  C.I ).    

#### 2 sample t_test

In [87]:
from scipy.stats import ttest_ind

In [88]:
df_no = df[df["Churn"]=='No']

In [89]:
df_yes = df[df["Churn"]=='Yes']

In [90]:
P_value_1 = ttest_ind(df_yes["MonthlyCharges"],df_no["MonthlyCharges"])
P_value_1

Ttest_indResult(statistic=16.53673801593631, pvalue=2.706645606888261e-60)

In [91]:
P_value_2 = ttest_ind(df_yes["tenure"],df_no["tenure"])
P_value_2

Ttest_indResult(statistic=-31.57955051135377, pvalue=7.99905796059022e-205)

#### Chisquare test

In [92]:
from scipy.stats import chi2_contingency

In [93]:
pd.crosstab(df["Churn"],df["gender"])

gender  Female  Male
Churn               
No        2549  2625
Yes        939   930

In [94]:
p_value_3 = chi2_contingency(pd.crosstab(df["Churn"],df["gender"]))
p_value_3

(0.4840828822091383,
 0.48657873605618596,
 1,
 array([[2562.38989067, 2611.61010933],
        [ 925.61010933,  943.38989067]]))

In [95]:
pd.crosstab(df["Churn"],df["SeniorCitizen"])

SeniorCitizen     0    1
Churn                   
No             4508  666
Yes            1393  476

In [96]:
p_value_4 = chi2_contingency(pd.crosstab(df["Churn"],df["SeniorCitizen"]))
p_value_4

(159.42630036838742,
 1.510066805092378e-36,
 1,
 array([[4335.05239245,  838.94760755],
        [1565.94760755,  303.05239245]]))

In [97]:
pd.crosstab(df["Churn"],df["Partner"])

Partner    No   Yes
Churn              
No       2441  2733
Yes      1200   669

In [98]:
p_value_4 = chi2_contingency(pd.crosstab(df["Churn"],df["Partner"]))
p_value_4

(158.7333820309922,
 2.1399113440759935e-36,
 1,
 array([[2674.78830044, 2499.21169956],
        [ 966.21169956,  902.78830044]]))

In [99]:
pd.crosstab(df["Churn"],df["Dependents"])

Dependents    No   Yes
Churn                 
No          3390  1784
Yes         1543   326

In [100]:
p_value_5 = chi2_contingency(pd.crosstab(df["Churn"],df["Dependents"]))
p_value_5

(189.12924940423474,
 4.9249216612154196e-43,
 1,
 array([[3623.93042737, 1550.06957263],
        [1309.06957263,  559.93042737]]))

In [101]:
pd.crosstab(df["Churn"],df["PhoneService"])

PhoneService   No   Yes
Churn                  
No            512  4662
Yes           170  1699

In [102]:
p_value_6 = chi2_contingency(pd.crosstab(df["Churn"],df["PhoneService"]))
p_value_6

(0.9150329892546948,
 0.3387825358066928,
 1,
 array([[ 501.01774812, 4672.98225188],
        [ 180.98225188, 1688.01774812]]))

In [103]:
pd.crosstab(df["Churn"],df["OnlineBackup"])

OnlineBackup    No  No internet service   Yes
Churn                                        
No            1855                 1413  1906
Yes           1233                  113   523

In [104]:
p_value_7 = chi2_contingency(pd.crosstab(df["Churn"],df["OnlineBackup"]))
p_value_7

(601.8127901134089,
 2.0797592160865457e-131,
 2,
 array([[2268.53783899, 1121.04557717, 1784.41658384],
        [ 819.46216101,  404.95442283,  644.58341616]]))

In [105]:
pd.crosstab(df["Churn"],df["TechSupport"])

TechSupport    No  No internet service   Yes
Churn                                       
No           2027                 1413  1734
Yes          1446                  113   310

In [106]:
p_value_8 = chi2_contingency(pd.crosstab(df["Churn"],df["TechSupport"]))
p_value_8

(828.1970684587393,
 1.4430840279999813e-180,
 2,
 array([[2551.37043873, 1121.04557717, 1501.5839841 ],
        [ 921.62956127,  404.95442283,  542.4160159 ]]))

In [107]:
pd.crosstab(df["Churn"],df["StreamingTV"])

StreamingTV    No  No internet service   Yes
Churn                                       
No           1868                 1413  1893
Yes           942                  113   814

In [108]:
p_value_9 = chi2_contingency(pd.crosstab(df["Churn"],df["StreamingTV"]))
p_value_9

(374.20394331098134,
 5.528994485739024e-82,
 2,
 array([[2064.31066307, 1121.04557717, 1988.64375976],
        [ 745.68933693,  404.95442283,  718.35624024]]))

In [109]:
pd.crosstab(df["Churn"],df["Contract"])

Contract  Month-to-month  One year  Two year
Churn                                       
No                  2220      1307      1647
Yes                 1655       166        48

In [110]:
p_value_10 = chi2_contingency(pd.crosstab(df["Churn"],df["Contract"]))
p_value_10

(1184.5965720837926,
 5.863038300673391e-258,
 2,
 array([[2846.69175067, 1082.11018032, 1245.198069  ],
        [1028.30824933,  390.88981968,  449.801931  ]]))

In [111]:
pd.crosstab(df["Churn"],df["PaperlessBilling"])

PaperlessBilling    No   Yes
Churn                       
No                2403  2771
Yes                469  1400

In [112]:
p_value_11 = chi2_contingency(pd.crosstab(df["Churn"],df["PaperlessBilling"]))
p_value_11

(258.27764906707307,
 4.073354668665985e-58,
 1,
 array([[2109.85773108, 3064.14226892],
        [ 762.14226892, 1106.85773108]]))

In [113]:
pd.crosstab(df["Churn"],df["PaymentMethod"])

PaymentMethod  Bank transfer (automatic)  Credit card (automatic)  \
Churn                                                               
No                                  1286                     1290   
Yes                                  258                      232   

PaymentMethod  Electronic check  Mailed check  
Churn                                          
No                         1294          1304  
Yes                        1071           308

In [114]:
p_value_12 = chi2_contingency(pd.crosstab(df["Churn"],df["PaymentMethod"]))
p_value_12

(648.1423274814,
 3.6823546520097993e-140,
 3,
 array([[1134.26891949, 1118.10705665, 1737.40025557, 1184.22376828],
        [ 409.73108051,  403.89294335,  627.59974443,  427.77623172]]))

#### 4. Interpret the results 

* Here we are cosidering 95% confidence interval so hence for the features which are having p_values greater than 0.05 we reject the null hypothesis and for the features which have their p_values less than 0.05 we fail to reject null hypothesis.

-----------

<span style="font-family: Arial; font-weight:bold;font-size:1.5em;color:#7d5b06;">3).Read he data set(Admission.xlsx) consists of complete educational details of students right from their schooling to MBA and previous work experience. Salary is the target variable in the data.Perform the following tasks on the data :


1. List out the numerical and categorical features in the dataset and mention the possible statistical hypothesis test for give features in the dataset(2 marks)


2. State the null and alternative hypothesis for any one of the test mention in the question number one(2 marks)

3. Now perform required statistical tests on the data to determine what are the significant features in the data with respect 
to  target variable(95%  C.I ).      (5 Marks)

4. Interpret the results  (2 Marks)

5. Build a model and find the coefficient and intercept value ? (4 Marks)

In [ ]:
df = pd.read_excel("Admission.xlsx")

#### 1. List out the numerical and categorical features in the dataset and mention the possible statistical hypothesis test for give features in the dataset(2 marks)

Here our target variable is continuos variable so if there is atleast one continuos variable we go for either 2 sample t test or Anova based on the classes.

Gender                 
Percent_SSC     
Percent_HSC            
Percent_Degree         
Experience_Yrs         
Percentile_ET          
Percent_MBA            
Marks_Communication    
Marks_Projectwork      
Marks_BOCA             
Placement

To check the significance of these variables on Salary variable we need to conduct 2 sample t test.

Board_SSC           
Board_HSC              
Stream_HSC             
Course_Degree       
Entrance_Test          
Specialization_MBA     

To check the significance of these variables on Salary variable we need to conduct ANOVA test.

#### 2.State the null and alternative hypothesis for any one of the test mention in the question number one(2 marks)

#### NUll Hypothesis : 

* H0 : There is no significant differnece between the means of variables.

#### Alternate Hypothesis :

* H1 : There is a significant differnece between the means of variables.

####  3. Now perform required statistical tests on the data to determine what are the significant features in the data with respect to target variable(95%  C.I ).

### 2 sample t test

In [53]:
from scipy.stats import ttest_ind

In [54]:
df_male = df[df["Gender"]=='M']
df_female = df[df["Gender"]=='F']

In [55]:
P_value_1 = ttest_ind(df_male['Salary'],df_female['Salary'])
P_value_1

Ttest_indResult(statistic=2.57570858963061, pvalue=0.010371783657249766)

In [31]:
P_value_2 = ttest_ind(df['Percent_SSC'],df['Salary'])
P_value_2

Ttest_indResult(statistic=-31.311273024426754, pvalue=5.143802562197286e-140)

In [32]:
P_value_3 = ttest_ind(df['Percent_HSC'],df['Salary'])
P_value_3

Ttest_indResult(statistic=-31.311395545437126, pvalue=5.13505773836659e-140)

In [33]:
P_value_4 = ttest_ind(df['Percent_Degree'],df['Salary'])
P_value_4

Ttest_indResult(statistic=-31.311511630009665, pvalue=5.126786029214024e-140)

In [37]:
P_value_5 = ttest_ind(df['Experience_Yrs'],df['Salary'])
P_value_5

Ttest_indResult(statistic=-31.320447769273983, pvalue=4.528451336654958e-140)

In [56]:
P_value_6 = ttest_ind(df['Percentile_ET'],df['Salary'])
P_value_6

Ttest_indResult(statistic=-31.31266157420177, pvalue=5.045562251886447e-140)

In [57]:
P_value_7 = ttest_ind(df['Percent_MBA'],df['Salary'])
P_value_7

Ttest_indResult(statistic=-31.311699795752272, pvalue=5.113406413800204e-140)

In [58]:
P_value_8 = ttest_ind(df["Marks_Communication"],df['Salary'])
P_value_8

Ttest_indResult(statistic=-31.311861032603897, pvalue=5.101969380253429e-140)

In [59]:
P_value_9 = ttest_ind(df['Marks_Projectwork'],df['Salary'])
P_value_9

Ttest_indResult(statistic=-31.31074256393083, pvalue=5.181835875206455e-140)

In [60]:
P_value_10 = ttest_ind(df['Marks_BOCA'],df['Salary'])
P_value_10

Ttest_indResult(statistic=-31.3113121965867, pvalue=5.141005066774011e-140)

In [61]:
P_value_10 = ttest_ind(df['Marks_BOCA'],df['Salary'])
P_value_10

Ttest_indResult(statistic=-31.3113121965867, pvalue=5.141005066774011e-140)

In [63]:
df_placed = df[df["Placement"]=="Placed"]
df_not_placed = df[df["Placement"]=="Not Placed"]

In [64]:
P_value_11 = ttest_ind(df_placed['Salary'],df_not_placed['Salary'])
P_value_11

Ttest_indResult(statistic=26.120992523456167, pvalue=1.3521256125354252e-87)

#### Anova test 

In [65]:
from scipy.stats import f_oneway

In [66]:
df_others = df[df["Board_SSC"]=="Others"]
df_CBSE = df[df["Board_SSC"]=="CBSE"]
df_ICSE = df[df["Board_SSC"]=="ICSE"]

In [67]:
P_value_12 = f_oneway(df_others['Salary'],df_CBSE['Salary'],df_ICSE['Salary'])
P_value_12

F_onewayResult(statistic=0.5453489346394286, pvalue=0.5800831293908766)

In [68]:
df_Others = df[df["Board_HSC"]=="Others"]
df_cbse = df[df["Board_HSC"]=="CBSE"]
df_ISC = df[df["Board_HSC"]=="ISC"]

In [69]:
P_value_13 = f_oneway(df_Others['Salary'],df_cbse['Salary'],df_ISC['Salary'])
P_value_13

F_onewayResult(statistic=0.288768177728968, pvalue=0.7493467322696925)

In [70]:
df_Commerce = df[df["Stream_HSC"]=="Commerce"]
df_Science = df[df["Stream_HSC"]=="Science"]
df_Arts = df[df["Stream_HSC"]=="Arts"]

In [71]:
P_value_14 = f_oneway(df_Commerce['Salary'],df_Science['Salary'],df_Arts['Salary'])
P_value_14

F_onewayResult(statistic=0.9378565284715171, pvalue=0.39235161561416954)

In [72]:
df_Management = df[df["Course_Degree"]=="Management"]
df_commerce = df[df["Course_Degree"]=="Commerce"]
df_engineering = df[df["Course_Degree"]=="Engineering"]
df_computer_Application = df[df["Course_Degree"]=="Computer Applications"]
df_science = df[df["Course_Degree"]=="Science"]
df_arts = df[df["Course_Degree"]=="Arts"]
df_other = df[df["Course_Degree"]=="Others"]

In [73]:
P_value_15 = f_oneway(df_Management["Salary"],df_commerce["Salary"],df_engineering["Salary"],df_computer_Application["Salary"],df_science["Salary"],df_arts["Salary"],df_other["Salary"])
P_value_15

F_onewayResult(statistic=1.3661808647106837, pvalue=0.2271129436118772)

In [74]:
df_Mat = df[df["Entrance_Test"]=="MAT"]
df_kmat = df[df["Entrance_Test"]=="K-MAT"]
df_cat = df[df["Entrance_Test"]=="CAT"]
df_pgcet = df[df["Entrance_Test"]=="PGCET"]
df_gcet = df[df["Entrance_Test"]=="GCET"]
df_gsat = df[df["Entrance_Test"]=="G-SAT"]
df_xat = df[df["Entrance_Test"]=="XAT"]
df_gmat = df[df["Entrance_Test"]=="G-MAT"]

In [75]:
P_value_16 = f_oneway(df_Mat["Salary"],df_kmat["Salary"],df_cat["Salary"],df_pgcet["Salary"],df_gcet["Salary"],df_gsat["Salary"],df_xat["Salary"],df_gmat["Salary"])
P_value_16

F_onewayResult(statistic=1.4423761880706971, pvalue=0.18684449983570944)

In [76]:
df_MF =   df[df["Specialization_MBA"]=="Marketing & Finance"]
df_MHR =  df[df["Specialization_MBA"]=="Marketing & HR"]
df_MIB =  df[df["Specialization_MBA"]=="Marketing & IB"]

In [77]:
p_value_17 = f_oneway(df_MF["Salary"],df_MHR["Salary"],df_MIB["Salary"])
p_value_17

F_onewayResult(statistic=1.8106456622904814, pvalue=0.16492766587692093)

### Interpreting results

* Here we are cosidering 95% confidence interval so hence for the features which are having p_values greater than 0.05 we reject the null hypothesis and for the features which have their p_values less than 0.05 we fail to reject null hypothesis.

#### 5. Build a model and find the coefficient and intercept value ?

In [28]:
df.head()

SlNo Gender  Percent_SSC Board_SSC  Percent_HSC Board_HSC Stream_HSC  \
0     1      M        62.00    Others        88.00    Others   Commerce   
1     2      M        76.33      ICSE        75.33    Others    Science   
2     3      M        72.00    Others        78.00    Others   Commerce   
3     4      M        60.00      CBSE        63.00      CBSE       Arts   
4     5      M        61.00      CBSE        55.00       ISC    Science   

   Percent_Degree          Course_Degree  Experience_Yrs Entrance_Test  \
0           52.00                Science               0           MAT   
1           75.48  Computer Applications               1           MAT   
2           66.63            Engineering               0           NaN   
3           58.00             Management               0           MAT   
4           54.00            Engineering               1           MAT   

   Percentile_ET  Percent_MBA   Specialization_MBA  Marks_Communication  \
0           55.0        58.80       Marketing & HR                   50   
1           86.5        66.28  Marketing & Finance                   69   
2            0.0        52.91  Marketing & Finance                   50   
3           75.0        57.80  Marketing & Finance                   54   
4           66.0        59.43       Marketing & HR                   52   

   Marks_Projectwork  Marks_BOCA Placement  Salary  
0                 65          74    Placed  270000  
1                 70          75    Placed  200000  
2                 61          59    Placed  240000  
3                 66          62    Placed  250000  
4                 65          67    Placed  180000

In [29]:
df.isnull().sum()

SlNo                    0
Gender                  0
Percent_SSC             0
Board_SSC               0
Percent_HSC             0
Board_HSC               0
Stream_HSC              0
Percent_Degree          0
Course_Degree           0
Experience_Yrs          0
Entrance_Test          67
Percentile_ET           0
Percent_MBA             0
Specialization_MBA      0
Marks_Communication     0
Marks_Projectwork       0
Marks_BOCA              0
Placement               0
Salary                  0
dtype: int64

In [32]:
df["Entrance_Test"].value_counts()

MAT      332
K-MAT     24
CAT       22
PGCET      8
GCET       2
G-SAT      1
XAT        1
G-MAT      1
Name: Entrance_Test, dtype: int64

In [31]:
df["Entrance_Test"].fillna(value='MAT',inplace=True)

In [37]:
df_cat = df[["Gender",'Board_SSC',"Board_HSC","Stream_HSC","Course_Degree","Entrance_Test","Specialization_MBA","Placement"]]

In [48]:
df_num = df[['Percent_SSC','Percent_HSC',"Percent_Degree","Experience_Yrs","Percentile_ET","Percent_MBA","Marks_Communication","Marks_Projectwork","Marks_BOCA","Salary"]]

In [49]:
df_cat = pd.get_dummies(df_cat,drop_first=True)

In [63]:
final_df = pd.concat([df_num,df_cat],axis=1)

In [64]:
final_df.shape

(391, 33)

In [67]:
x = final_df.drop("Salary",axis=1)

In [68]:
y = final_df["Salary### Step8:  Intercept value 

regressor.intercept_ "]

In [69]:
from sklearn.model_selection import train_test_split

In [70]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 1/3, random_state = 0)

In [71]:
from sklearn.linear_model import LinearRegression

In [72]:
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [73]:
#Intercept value 

In [74]:
regressor.intercept_ 

-188725.94217111528

In [76]:
#Coefficients value

In [77]:
regressor.coef_ 

array([-2.92437240e+02,  3.51685962e+02,  8.00339317e+02,  2.08519210e+04,
        1.67879549e+01,  5.05711097e+02,  1.40014186e+03,  2.09031458e+02,
        2.67892489e+02,  3.81058202e+04, -3.32552908e+04, -1.73339452e+04,
        3.01400986e+04,  3.27732378e+03,  5.49553018e+04,  4.35303375e+04,
       -4.45429381e+04, -2.94353043e+04,  1.21738414e+04, -4.58405607e+04,
       -4.78496264e+04, -5.93478320e+04, -7.85734901e+03, -7.39009681e+04,
       -5.50044865e+04,  3.31471362e+04, -4.03222235e+04, -9.67365867e+03,
       -9.33578215e+03, -2.84382378e+04, -2.74731288e+04,  2.72347791e+05])